name: Error
description: Error found during review proces
title: "[Err]: "
labels: []
body:
  - type: input
    id: module
    attributes:
      label: Module
      description:  Module where error was found
      placeholder: ex. app.py
    validations:
      required: false
  - type: input
    id: line
    attributes:
      label: Line
      description:  place in file
      placeholder: ex. 69
    validations:
      required: false
  - type: textarea
    id: subject
    attributes:
      label: Error
      description: Describe error
    validations:
      required: false
